"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Eye, EyeOff, Headphones, Mic, Pause, Play, Repeat2, SkipBack, SkipForward, Square, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { splitListeningPhrases } from "@/lib/listening";

type Language={id:string;name:string;code:string;speechLocale:string|null;speechVoiceName:string|null;samples:string[]};
type Action=(formData:FormData)=>unknown|Promise<unknown>;
export function ListeningWorkspace({languages,saveRound,initialLanguageId}:{languages:Language[];saveRound:Action;initialLanguageId?:string}){
 const initial=initialLanguageId&&languages.some(l=>l.id===initialLanguageId)?initialLanguageId:languages[0]?.id??"";
 const [runId]=useState(()=>crypto.randomUUID());
 const [languageId,setLanguageId]=useState(initial);const language=languages.find(l=>l.id===languageId);const [text,setText]=useState(language?.samples[0]??"");const [index,setIndex]=useState(0);const [rate,setRate]=useState(.9);const [loop,setLoop]=useState(false);const [hidden,setHidden]=useState(false);const [playing,setPlaying]=useState(false);const [played,setPlayed]=useState(false);const [recording,setRecording]=useState(false);const [recordingUrl,setRecordingUrl]=useState<string|null>(null);const [micState,setMicState]=useState("");const [voice,setVoice]=useState("talkie");const [browserVoices,setBrowserVoices]=useState<SpeechSynthesisVoice[]>([]);const [submitted,setSubmitted]=useState(false);
 const phrases=useMemo(()=>splitListeningPhrases(text),[text]);const phrase=phrases[Math.min(index,Math.max(0,phrases.length-1))]??text;const audioRef=useRef<HTMLAudioElement|null>(null);const audioUrlRef=useRef<string|null>(null);const loopRef=useRef(loop);const recorderRef=useRef<MediaRecorder|null>(null);const streamRef=useRef<MediaStream|null>(null);const chunksRef=useRef<Blob[]>([]);const recordingUrlRef=useRef<string|null>(null);
 const stop=useCallback(()=>{loopRef.current=false;setLoop(false);audioRef.current?.pause();if(audioRef.current)audioRef.current.currentTime=0;window.speechSynthesis?.cancel();setPlaying(false)},[]);
 const clearRecording=useCallback(()=>{if(recorderRef.current?.state==="recording")recorderRef.current.stop();streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(recordingUrlRef.current)URL.revokeObjectURL(recordingUrlRef.current);recordingUrlRef.current=null;setRecordingUrl(null);setRecording(false)},[]);
 const fallbackSpeak=useCallback(()=>{if(!phrase||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(phrase);utterance.lang=language?.speechLocale??language?.code??"en";utterance.rate=rate;const selected=browserVoices.find(item=>item.name===voice)||browserVoices.find(item=>item.name===language?.speechVoiceName);if(selected)utterance.voice=selected;utterance.onstart=()=>{setPlaying(true);setPlayed(true)};utterance.onend=()=>{setPlaying(false);if(loopRef.current)window.setTimeout(()=>window.speechSynthesis.speak(utterance),250)};utterance.onerror=()=>setPlaying(false);window.speechSynthesis.speak(utterance)},[phrase,language,rate,browserVoices,voice]);
 const play=useCallback(async()=>{if(!phrase)return;if(playing){audioRef.current?.pause();window.speechSynthesis?.pause();setPlaying(false);return}if(voice!=="talkie"){fallbackSpeak();return}if(audioRef.current&&audioRef.current.currentTime>0&&!audioRef.current.ended){audioRef.current.playbackRate=rate;await audioRef.current.play();setPlaying(true);return}try{const response=await fetch("/api/tts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:phrase,locale:language?.speechLocale??language?.code,voice:language?.speechVoiceName})});if(!response.ok)throw new Error("server TTS unavailable");if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current);const url=URL.createObjectURL(await response.blob());audioUrlRef.current=url;const audio=new Audio(url);audioRef.current=audio;audio.playbackRate=rate;audio.onplay=()=>{setPlaying(true);setPlayed(true)};audio.onpause=()=>setPlaying(false);audio.onended=()=>{setPlaying(false);if(loopRef.current)window.setTimeout(()=>{audio.currentTime=0;void audio.play()},250)};await audio.play()}catch{fallbackSpeak()}},[phrase,playing,rate,language,voice,fallbackSpeak]);
 const startRecording=async()=>{setMicState("");if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setMicState("Recording is not supported in this browser.");return}try{clearRecording();const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;chunksRef.current=[];const recorder=new MediaRecorder(stream);recorderRef.current=recorder;recorder.ondataavailable=event=>{if(event.data.size)chunksRef.current.push(event.data)};recorder.onerror=()=>{setMicState("Recording was interrupted. Please try again.");clearRecording()};recorder.onstop=()=>{stream.getTracks().forEach(track=>track.stop());const url=URL.createObjectURL(new Blob(chunksRef.current,{type:recorder.mimeType}));recordingUrlRef.current=url;setRecordingUrl(url);setRecording(false)};recorder.start();setRecording(true)}catch(error){setMicState(error instanceof DOMException&&error.name==="NotAllowedError"?"Microphone permission was denied. Listening playback still works.":"No usable microphone was found.")}};
 useEffect(()=>{loopRef.current=loop},[loop]);
 useEffect(()=>{const update=()=>setBrowserVoices(window.speechSynthesis?.getVoices().filter(item=>(item.lang||"").toLowerCase().startsWith((language?.code??"").toLowerCase()))??[]);update();window.speechSynthesis?.addEventListener("voiceschanged",update);return()=>window.speechSynthesis?.removeEventListener("voiceschanged",update)},[language?.code]);
 useEffect(()=>{setIndex(0);setPlayed(false);setSubmitted(false);stop();clearRecording()},[languageId,text,stop,clearRecording]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.target instanceof HTMLSelectElement)return;if(event.code==="Space"){event.preventDefault();void play()}else if(event.key==="ArrowLeft")setIndex(i=>Math.max(0,i-1));else if(event.key==="ArrowRight")setIndex(i=>Math.min(Math.max(0,phrases.length-1),i+1));else if(event.key.toLowerCase()==="r"){stop();void play()}else if(event.key.toLowerCase()==="h")setHidden(v=>!v);else if(event.key==="Escape"){stop();if(recorderRef.current?.state==="recording")recorderRef.current.stop()}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[play,phrases.length,stop]);
 useEffect(()=>()=>{stop();clearRecording();if(audioUrlRef.current)URL.revokeObjectURL(audioUrlRef.current)},[stop,clearRecording]);
 const completionKey=useMemo(()=>`${runId}:${languageId}:${index}`,[runId,languageId,index]);
 return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_22rem]"><section className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap gap-3"><label className="text-xs font-medium">Language<select value={languageId} onChange={event=>{const next=languages.find(item=>item.id===event.target.value);setLanguageId(event.target.value);setText(next?.samples[0]??"")}} className="mt-1 block h-9 rounded-md border bg-background px-2">{languages.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs font-medium">Voice<select value={voice} onChange={event=>setVoice(event.target.value)} className="mt-1 block h-9 rounded-md border bg-background px-2"><option value="talkie">Talkie voice</option>{browserVoices.map(item=><option key={item.name} value={item.name}>{item.name}</option>)}</select></label><label className="text-xs font-medium">Speed<select value={rate} onChange={event=>setRate(Number(event.target.value))} className="mt-1 block h-9 rounded-md border bg-background px-2">{[.65,.8,.9,1,1.15].map(value=><option key={value} value={value}>{value}×</option>)}</select></label></div><label className="mt-4 block text-sm font-medium">Practice text<textarea value={text} onChange={event=>setText(event.target.value)} maxLength={1000} className="mt-1 min-h-28 w-full rounded-xl border bg-background p-3"/></label>
 <div className="mt-5 rounded-2xl border border-indigo-200 bg-indigo-50/50 p-6 text-center dark:border-indigo-900 dark:bg-indigo-950/30"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-indigo-700">Phrase {Math.min(index+1,phrases.length||1)} / {phrases.length||1}</p><p className={`mt-5 min-h-16 text-2xl font-semibold ${hidden?"select-none blur-md":""}`}>{phrase||"Add practice text to begin."}</p><div className="mt-5 flex flex-wrap justify-center gap-2"><Button variant="outline" aria-label="Previous phrase" onClick={()=>setIndex(i=>Math.max(0,i-1))}><SkipBack className="h-4 w-4"/></Button><Button onClick={()=>void play()} className="bg-indigo-600 text-white hover:bg-indigo-700">{playing?<Pause className="mr-2 h-4 w-4"/>:<Play className="mr-2 h-4 w-4"/>}{playing?"Pause":"Play"}</Button><Button variant="outline" aria-label="Next phrase" onClick={()=>setIndex(i=>Math.min(Math.max(0,phrases.length-1),i+1))}><SkipForward className="h-4 w-4"/></Button><Button variant="outline" onClick={()=>{setLoop(value=>{loopRef.current=!value;return !value});if(loop)stop()}} className={loop?"border-indigo-500 text-indigo-700":""}><Repeat2 className="mr-2 h-4 w-4"/>Loop</Button><Button variant="outline" onClick={()=>setHidden(v=>!v)}>{hidden?<Eye className="mr-2 h-4 w-4"/>:<EyeOff className="mr-2 h-4 w-4"/>}{hidden?"Reveal":"Hide"}</Button></div></div>
 <form action={async data=>{if(!played||submitted)return;await saveRound(data);setSubmitted(true)}} className="mt-4 flex justify-end"><input type="hidden" name="languageId" value={languageId}/><input type="hidden" name="sourceText" value={phrase}/><input type="hidden" name="sourceType" value={language?.samples.includes(text)?"TALKIE":"USER_TEXT"}/><input type="hidden" name="completionKey" value={completionKey}/><button disabled={!phrase||!played||submitted} className="rounded-md bg-rose-600 px-3 py-2 text-sm font-medium text-white disabled:opacity-50">{submitted?"Round recorded":"Complete listening round"}</button></form></section>
 <aside className="rounded-2xl border p-5"><div className="flex items-center gap-2"><Headphones className="h-5 w-5 text-rose-600"/><h2 className="font-semibold">Compare shadowing</h2></div><p className="mt-2 text-sm text-muted-foreground">Source and recording stay separate. Your recording never leaves this browser.</p><div className="mt-5 grid gap-3"><Button variant="outline" onClick={()=>void play()}><Play className="mr-2 h-4 w-4"/>Replay source</Button><Button variant="outline" onClick={recording?()=>recorderRef.current?.stop():startRecording}>{recording?<Square className="mr-2 h-4 w-4"/>:<Mic className="mr-2 h-4 w-4"/>}{recording?"Stop recording":"Record attempt"}</Button>{recordingUrl&&<><audio controls src={recordingUrl} className="w-full"/><button onClick={clearRecording} className="inline-flex items-center text-xs text-rose-600"><Trash2 className="mr-1 h-3.5 w-3.5"/>Clear recording</button></>}</div>{micState&&<p className="mt-4 rounded-md bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950" role="status">{micState}</p>}<p className="mt-5 text-xs text-muted-foreground">Keyboard: Space play/pause · ←/→ phrases · R replay · H transcript · Esc stop</p></aside></div>;
}
